"""
This script reads the cleaned dataset generated by `data_cleaning.py` and
creates plots for each zip showing rent and the number of business openings.

Arguments:
  python SCRIPTS/eda.py                # plot all ZIPs found in the dataset
  python SCRIPTS/eda.py --zip 60601    # plot a specific ZIP code
"""

import argparse
from pathlib import Path

import matplotlib.dates as mdates
import matplotlib.pyplot as plt
from matplotlib.ticker import StrMethodFormatter
import pandas as pd

# Plot rent and business openings for a single ZIP code.
def plot_zip(zip_code, df, output_dir):
    sub = df[df["ZIP CODE"] == int(zip_code)]
    sub = sub.sort_values("month")

    plt.style.use("default")
    fig, ax1 = plt.subplots(figsize=(14, 7))
    fig.patch.set_facecolor("white")
    ax1.set_facecolor("white")
    ax2 = ax1.twinx()
    ax2.set_facecolor("white")

    ax1.plot(sub["month"], sub["rent_price"], color="red", linewidth=2, label="Rent")

    ax1.set_xlabel("Month")
    ax1.set_ylabel("Rent Price ($)", color="red")
    ax2.set_ylabel("Business Openings", color="blue")

    ax1.tick_params(axis="y", labelcolor="red")

    ax1.yaxis.set_major_formatter(StrMethodFormatter("{x:,.0f}"))

    ax1.xaxis.set_major_locator(mdates.MonthLocator(interval=4))
    ax1.xaxis.set_major_formatter(mdates.DateFormatter("%b %Y"))
    fig.autofmt_xdate(rotation=25)

    ax1.grid(True, color="black", linestyle="--", alpha=0.2)

    title = f"Rent and Business Openings per month in ZIP Code {zip_code}"
    ax1.set_title(title, fontweight="bold")

    ax2.bar(sub["month"], sub["business_openings"].fillna(0), width=18, color="#1f77b4", alpha=0.75)

    ax2.set_ylabel("Business openings", color="#1f77b4")
    ax2.tick_params(axis="y", labelcolor="#1f77b4")

    ax1.legend(loc="upper left", framealpha=0.8)

    fig.tight_layout()
    out_path = output_dir / f"rent_and_business_monthly_{zip_code}.png"
    fig.savefig(out_path, dpi=150)
    plt.close(fig)

    print(f"Saved plot: {zip_code}")


def main():
    parser = argparse.ArgumentParser(description="EDA plots for rent vs business openings.")
    parser.add_argument(
        "--zip",
        dest="zip_code",
        help="ZIP code to plot (e.g. 60601). If omitted, plots for all ZIP codes (or top N if --top is set).",
    )
    args = parser.parse_args()

    project_root = Path(__file__).resolve().parent.parent
    data_path = project_root / "DATA" / "cleaned_chicago_dataset.csv"
    output_path = project_root / "OUTPUT"
    output_path.mkdir(parents=True, exist_ok=True)

    df = pd.read_csv(data_path)
    df["month"] = pd.to_datetime(df["month"], errors="coerce")

    if args.zip_code:
        plot_zip(args.zip_code, df, output_path)
        return

    zip_codes = df["ZIP CODE"].dropna().unique().astype(int)

    for z in sorted(zip_codes):
        plot_zip(str(z), df, output_path)


if __name__ == "__main__":
    main()
